import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import TanstackProvider from "@/components/providers/tanstack";
import NextAuthSessionProvider from "@/components/providers/session";
import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={`${inter.className} min-w-[380px]`}>
				<NextAuthSessionProvider>
					<TanstackProvider>
						<main className='flex flex-col justify-between gap-4 min-h-screen bg-slate-50'>
							<Header />
							{children}
							<Footer />
						</main>
					</TanstackProvider>
				</NextAuthSessionProvider>
			</body>
		</html>
	);
}
